/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type Formule = {
  _id: string;
  _type: "formule";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nom?: string;
  prix?: number;
};

export type Ingredient = {
  _id: string;
  _type: "ingredient";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nom?: string;
};

export type Salade = {
  _id: string;
  _type: "salade";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nom?: string;
  prix?: number;
  ingredients?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "ingredient";
  }>;
};

export type Dessert = {
  _id: string;
  _type: "dessert";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nom?: string;
  prix?: number;
};

export type Plat = {
  _id: string;
  _type: "plat";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nom?: string;
  prix?: number;
};

export type Entree = {
  _id: string;
  _type: "entree";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nom?: string;
  prix?: number;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData | Formule | Ingredient | Salade | Dessert | Plat | Entree;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/desserts/getAllDesserts.ts
// Variable: ALL_DESSERTS_QUERY
// Query: *[                _type == "dessert"            ] | order(name asc)
export type ALL_DESSERTS_QUERYResult = Array<{
  _id: string;
  _type: "dessert";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nom?: string;
  prix?: number;
}>;

// Source: ./src/sanity/lib/dishs/getAllDishs.ts
// Variable: ALL_DISHES_QUERY
// Query: *[                _type == "plat"            ] | order(name asc)
export type ALL_DISHES_QUERYResult = Array<{
  _id: string;
  _type: "plat";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nom?: string;
  prix?: number;
}>;

// Source: ./src/sanity/lib/options/getAllOptions.ts
// Variable: ALL_OPTIONS_QUERY
// Query: *[                _type == "formule"            ] | order(name desc)
export type ALL_OPTIONS_QUERYResult = Array<{
  _id: string;
  _type: "formule";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nom?: string;
  prix?: number;
}>;

// Source: ./src/sanity/lib/salades/getAllSalades.ts
// Variable: ALL_SALADES_QUERY
// Query: *[                _type == "salade"            ] | order(name asc)
export type ALL_SALADES_QUERYResult = Array<{
  _id: string;
  _type: "salade";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nom?: string;
  prix?: number;
  ingredients?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "ingredient";
  }>;
}>;

// Source: ./src/sanity/lib/starters/getAllStarters.ts
// Variable: ALL_STARTERS_QUERY
// Query: *[                _type == "entree"            ] | order(name asc)
export type ALL_STARTERS_QUERYResult = Array<{
  _id: string;
  _type: "entree";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nom?: string;
  prix?: number;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n            *[\n                _type == \"dessert\"\n            ] | order(name asc)\n        ": ALL_DESSERTS_QUERYResult;
    "\n            *[\n                _type == \"plat\"\n            ] | order(name asc)\n        ": ALL_DISHES_QUERYResult;
    "\n            *[\n                _type == \"formule\"\n            ] | order(name desc)\n        ": ALL_OPTIONS_QUERYResult;
    "\n            *[\n                _type == \"salade\"\n            ] | order(name asc)\n        ": ALL_SALADES_QUERYResult;
    "\n            *[\n                _type == \"entree\"\n            ] | order(name asc)\n        ": ALL_STARTERS_QUERYResult;
  }
}
