import type { Metadata } from "next";
import { Forum, Arizonia } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const forum = Forum({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-forum",
});
const arizonia = Arizonia({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-arizonia",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${forum.variable} ${arizonia.variable}  bg-[#0d0c0b] overflow-x-hidden`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
